### PR TITLE
fix: close storage on shutdown

### LINKED ISSUE #1523: Graceful shutdown should be supported
Today, dex dose not handle any signal from user or kubernetes. This might cause some resource open when dex process are killed, e.g. the storage.Close function never get called.

### PR DESCRIPTION
**Pull request by nabokihms**
#### Overview
Call the `Close` method on storage in case of graceful shutdown

#### What this PR does / why we need it
Closes #1523

#### Does this PR introduce a user-facing change?
```release-note
Close storage on graceful shutdown
```

### CODE REVIEW

File: cmd/dex/serve.go [hunk 1]
```diff
@@ -193,6 +202,8 @@ func runServe(options serveOptions) error {
 	if err != nil {
 		return fmt.Errorf("failed to initialize storage: %v", err)
 	}
+	defer closeStorage(logger, s)
```
Comment (sagikazarmark) [inline cmd/dex/serve.go:205]: I kinda think `defer s.Close()`  should be enough for now. Failure to close a storage is not actionable, we can't do anything with the fact that it failed.

Comment (nabokihms) [reply cmd/dex/serve.go:205]: Oh, ok. I will simplify it.

Incorrectly closing storage can affect the database, e.g., the connection may be left open. I thought this message can help with debugging problems on the storage side.

**Review by sagikazarmark — APPROVED** [review]
