### PR TITLE
Fix MySQL connection to use the provided port

### LINKED ISSUE #2098: Cannot specify MySQL port
#### Expected behavior (what you expected to happen)
Mysql can connect and init successful.
#### Actual behavior (what actually happened)
Mysql with port 3308 can not connect.
#### Steps to reproduce

1. ...
2. ...
3. ...

#### Environment

- Dex version: v2.28.1
- Storage type: mysql
- Installation type (official docker image, helm chart, etc.): docker image

#### Additional information for debugging (if necessary)

<details><summary>Configuration</summary><br><pre>
---
# first  storage config
## conn str: root:123456@tcp([myip])/dex_db?checkConnLiveness=false&parseTime=true&tls=false&maxAllowedPacket=0&transaction_isolation=%27SERIALIZABLE%27
storage:
  type: mysql
  config:
    host: "[myip]"
    port: 3308
    database: "dex_db"
    user: "root"
    password: "xxxxxx"
    maxOpenConns: 5
    maxIdleConns: 3
    connMaxLifetime: 30
    connectionTimeout: 3
    ssl:
      mode: "false"
# second storage config
## conn str: root:123456@tcp([myip]:3308)/dex_db?checkConnLiveness=false&parseTime=true&tls=false&maxAllowedPacket=0&transaction_isolation=%27SERIALIZABLE%27
storage:
  type: mysql
  config:
    # Add port to host can connect successful, but init error.
    host: "[myip]:3308"
    port: 3308
    database: "dex_db"
    user: "root"
    password: "xxxxxxx"
    maxOpenConns: 5
    maxIdleConns: 3
    connMaxLifetime: 30
    connectionTimeout: 3
    ssl:
      mode: "false"

</pre></details>

<details><summary>Logs</summary><br><pre>
1. first  storage config error:
time="2021-04-25T09:19:52Z" level=info msg="config issuer: http://127.0.0.1:5556/dex"
failed to initialize storage: Error 1049: Unknown database 'dex_db'

2. second storage config error:
failed to initialize storage: failed to perform migrations: update migration table: Error 1461: Can't create more than max_prepared_stmt_count statements (current value: 16382)
</pre></details>

### PR DESCRIPTION
**Pull request by sagikazarmark**
#### Overview

The MySQL storage connector now uses the `port` field to allow connecting to MySQL instances running on a non-standard port.

#### What this PR does / why we need it

Fixes #2098

#### Does this PR introduce a user-facing change?

```release-note
Fix MySQL connection to use the provided port
```

### CODE REVIEW

**Review by bonifaido — APPROVED** [review]

File: storage/sql/config.go [hunk 1]
```diff
@@ -242,6 +242,10 @@ func (s *MySQL) open(logger log.Logger) (*conn, error) {
 		if s.Host[0] != '/' {
 			cfg.Net = "tcp"
 			cfg.Addr = s.Host
+
+			if s.Port != 0 {
+				cfg.Addr = fmt.Sprintf("%s:%d", s.Host, s.Port)
```
Comment (nabokihms) [inline storage/sql/config.go:247]: Maybe it is better to use `net.JoinHostPort` to cover the case with IPv6 addresses? However, it is required port to be a string.

**Review by nabokihms — APPROVED** [review]
No concerns about this PR. Just left a little comment.

File: storage/sql/config.go (hunk 1 above)
Comment (sagikazarmark) [reply storage/sql/config.go]: Makes sense, thanks!
